### ISSUE TITLE
Vortex Finder

### ISSUE THREAD

**Issue by GuyRon1** [GuyRon1/FFT-Hydrodynamic-sensing#6]
https://github.com/GuyRon1/FFT-Hydrodynamic-sensing/blob/7558da8e514c187a63fed6971b76b1f51e21d591/vortex%20finder.ipynb#L1

Hi Alex,

I've been thinking more about calculating the frequency from the PIV data, and I believe the best approach is to set a vorticity threshold and define a region within the fluid, away from the cylinders and light bulb. Then, we could run a loop through all the images and count how often the vorticity exceeds this threshold. I am not sure how to determine an accurate threshold for this but, I will start experimenting with it to see if it's computationally efficient.

**Comment by alexlib** [comment]
I think first is to create a static mask that defines regions of the cylinders - then to define a region of interest between them and then look for vorticity only inside that region. there are too many small noisy vortices that will obscure the values of what you're looking for.

**Comment by GuyRon1** [comment]
Thank you Alex I will try that.
How big should my Area Of Interest be? I don't want to count the same
vorticity twice (in a set of following photos) but I don't want to miss a
vortex either by making the Area too small

**Comment by alexlib** [comment]
trial and error.
________________________________

**Comment by GuyRon1** [comment]
Alright, I will keep you updated
